"""Initial migration.

Revision ID: 4a685e984ef6
Revises: 
Create Date: 2021-10-19 18:57:29.813118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a685e984ef6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iss', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('auth_login_url', sa.Text(), nullable=True),
    sa.Column('auth_token_url', sa.Text(), nullable=True),
    sa.Column('key_set_url', sa.Text(), nullable=True),
    sa.Column('private_key_file', sa.Text(), nullable=True),
    sa.Column('public_key_file', sa.Text(), nullable=True),
    sa.Column('deployment_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lti_config')
    # ### end Alembic commands ###
