"""JWK

Revision ID: f509d1dbdddf
Revises: 4a685e984ef6
Create Date: 2021-11-02 15:52:44.276109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f509d1dbdddf'
down_revision = '4a685e984ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lti_config', sa.Column('public_jwk', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lti_config', 'public_jwk')
    # ### end Alembic commands ###
